
title: Portfolio
email: thuwebaramah@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  CyberSecurity Analyst | IT Specialist
twitter_username: t_thuweba
github_username: thuwebaramah
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Thuweba Ramadhan"
  avatar : "/assets/images/My Pic.jpeg"
  bio    : "IT & cybersecurity enthusiast <br>Focused on digital trust"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://thuwebaramah.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/t_thuweba"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thuwebaramah"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/thuwebaramah"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/thuwebaramah"

    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:thuwebaramah@gmail.com"

    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/thuwebaramah"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/t_twitter"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

minimal_mistakes_footer:
  powered_by: false
  custom_text: "© 2025 Thuweba Soud. All rights reserved."

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

favicon: /assets/images/icon.png
